apiVersion: v1
kind: Pod
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  name: shared-demo-reader
  namespace: {{ .Values.namespace }}
spec:
  volumes:
  - name: shared-vol
    persistentVolumeClaim:
      claimName: rwx-demo-shared-data
  terminationGracePeriodSeconds: 5
  containers:
  - image: busybox
    imagePullPolicy: Always
    name: busybox-reader
    volumeMounts:
    - name: shared-vol
      mountPath: "/mnt"
    command:
      - sh
    args:
      - -c
      - |
        echo "Sleeping for 120 seconds for writers to populate file"
        sleep 120
        tail -n 400 /mnt/shared.log
        sleep infinity
