clusterGroup:
  name: standalone
  isHubCluster: true
  namespaces:
    vault:
    openshift-cluster-csi-drivers:
      operatorGroup: true
      targetNamespaces: []
    config-demo:
    hello-world:
  subscriptions:
    openshift-sscsi:
      name: secrets-store-csi-driver-operator
      namespace: openshift-cluster-csi-drivers
      channel: stable
      source: redhat-operators
      sourceNamespace: openshift-marketplace
  argoProjects:
    - hub
    - config-demo
    - hello-world
  # Explicitly mention the cluster-state based overrides we plan to use for this pattern.
  # We can use self-referential variables because the chart calls the tpl function with these variables defined
  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
  # sharedValueFiles is a flexible mechanism that will add the listed valuefiles to every app defined in the
  # applications section.
  #
  # This kind of variable substitution will work with any of the variables the Validated Patterns operator knows
  # about and sets, so this is also possible, for example:
  #   - '/overrides/values-{{ $.Values.global.hubClusterDomain }}.yaml'
  #   - '/overrides/values-{{ $.Values.global.localClusterDomain }}.yaml'
  applications:
    vault:
      name: vault
      namespace: vault
      argoProject: hub
      annotations:
        argocd.argoproj.io/sync-wave: "5"
      repoURL: https://github.com/mhjacks/hashicorp-vault-chart.git
      chartVersion: add_csi
      path: "."
      extraValueFiles:
        - $patternref/overrides/values-vault-csi-tls-ca.yaml
      overrides:
        - name: vault.csi.enabled
          value: true
        - name: vault.csi.daemonSet.providersDir
          value: /etc/kubernetes/secrets-store-csi-providers
    openshift-sscsi-vault:
      name: openshift-sscsi-vault-config-demo
      namespace: config-demo
      argoProject: config-demo
      annotations:
        argocd.argoproj.io/sync-wave: "20"
      chart: openshift-sscsi-vault
      chartVersion: 0.0.*
      extraValueFiles:
        - $patternref/overrides/values-openshift-sscsi-vault-config-demo.yaml
      ignoreDifferences:
        - group: ""
          kind: ConfigMap
          name: openshift-sscsi-vault-vault-tls-ca
          namespace: vault
          jsonPointers:
            - /data
          jqPathExpressions:
            - .data
      syncPolicy:
        automated: {}
        retry:
          limit: 20
        syncOptions:
          - RespectIgnoreDifferences=true
      ssCsiWorkloadAuth:
        - serviceAccount: config-demo-sa
          namespace: config-demo
          cluster: hub
          roleSlug: config-demo-config-demo-sa-config-demo
    config-demo:
      name: config-demo
      namespace: config-demo
      argoProject: config-demo
      annotations:
        argocd.argoproj.io/sync-wave: "25"
      path: charts/all/config-demo
    hello-world:
      name: hello-world
      namespace: hello-world
      argoProject: hello-world
      path: charts/all/hello-world
  imperative:
    clusterRoleYaml:
      - apiGroups:
          - '*'
        resources:
          - '*'
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - ''
        resources:
          - configmaps
        verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://validatedpatterns.io/patterns/multicloud-gitops/mcg-imperative-actions/
    jobs:
      - name: hello-world
        # ansible playbook to be run
        playbook: rhvp.cluster_utils.hello_world
        # per playbook timeout in seconds
        timeout: 234
        # verbosity: "-v"
  extraObjects:
    secrets-store-csi-clustercsidriver:
      apiVersion: operator.openshift.io/v1
      kind: ClusterCSIDriver
      metadata:
        name: secrets-store.csi.k8s.io
        annotations:
          argocd.argoproj.io/sync-wave: "15"
      spec:
        managementState: Managed
        logLevel: Normal
        operatorLogLevel: Normal
