---
global:
  pattern: multicloud-gitops

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  # Needed by vault to avoid trying to set some security contexts which do not apply on openshift
  # See https://github.com/hashicorp/vault-helm/issues/343 for more infos
  openshift: true

# Enable vault dev server mode in vault
server:
  dev:
    enabled: true

main:
  clusterGroupName: hub
