---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    #clusterGroupChartVersion: "0.9.*"
    clusterGroupGitRepoUrl: https://github.com/mhjacks/clustergroup-chart.git
    clusterGroupGitRevision: test_tpl

