---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupGitRepoUrl: https://github.com/mhjacks/clustergroup-chart
    clusterGroupChartGitRevision: add_ansible_devmode
    # clusterGroupChartVersion: "0.9.*"
