---
global:
  pattern: multicloud-gitops
  clusterPushSecrets: true
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupGitRepoUrl: https://github.com/mhjacks/clustergroup-chart
    clusterGroupChartGitRevision: cluster_push_secrets
