---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  secretStore:
    backend: kubernetes
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
