{{- if eq $.Values.global.clusterPlatform "AWS" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portworx-prereq-clusterrolebinding
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-15"
subjects:
- kind: ServiceAccount
  name: portworx-prereq-sa
  namespace: {{ .Values.namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: portworx-prereq-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
