{{- if eq $.Values.global.clusterPlatform "AWS" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portworx-prereq-sa
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-hook: "PreSync"
    argocd.argoproj.io/sync-wave: "-10"
---
{{- end }}
