{{/* Only define this if there are any applicationSets defined */}}
{{- $namespace := cat $.Values.global.pattern $.Values.clusterGroup.name | replace " " "-" }}
{{- range .Values.clusterGroup.applicationsets }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
  labels:
    app: {{ .name }}
spec:
  generators: {{ .generators | toPrettyJson }}
  template:
    metadata:
      name: {{ coalesce .namespace $namespace }}
    spec:
      project: {{ .project }}
      {{- if .syncPolicy }}
      syncPolicy: {{ .syncPolicy | toPrettyJson }}
      {{- else }}
      syncPolicy:
        automated: {}
      {{- end }}
      {{- if .ignoreDifferences }}
      ignoreDifferences: {{ .ignoreDifferences | toPrettyJson }}
      {{- end }}
      source:
        repoURL: {{ coalesce .repoURL $.Values.global.repoURL }}
        targetRevision: {{ coalesce .targetRevision $.Values.global.targetRevision }} 
        {{- if .chart }}
        chart: {{ .chart }}
        {{- end }}
        {{- if .path }}
        path: {{ .path }}
        {{- end }}
        {{- if .plugin }}
        plugin: {{ .plugin }}
        {{- end }}
        {{- if not .kustomize }}
        helm:
          ignoreMissingValueFiles: true
          valueFiles: |
            - "/values-global.yaml"
            - "/values-{{ $.Values.clusterGroup.name }}.yaml"
        {{- range .extraValueFiles }}
            - "{{ . }}"
        {{- end }}
          #parameters:
          #  - name: global.hubClusterDomain
          #    value: {{ $.Values.global.hubClusterDomain }}
          #  - name: global.localClusterDomain
          #    value: {{ coalesce $.Values.global.localClusterDomain $.Values.global.hubClusterDomain }}
        {{- end }}
          #parameters:
          #  - name: global.repoURL
          #    value: $ARGOCD_APP_SOURCE_REPO_URL
          #  - name: global.targetRevision
          #    value: $ARGOCD_APP_SOURCE_TARGET_REVISION
          #  - name: global.namespace
          #    value: $ARGOCD_APP_NAMESPACE
          #  - name: global.pattern
          #    value: {{ $.Values.global.pattern }}
          #  - name: global.valuesDirectoryURL
          #    value: {{ coalesce .valuesDirectoryURL $.Values.global.valuesDirectoryURL }}
          #  - name: global.hubClusterDomain
          #    value: {{ $.Values.global.hubClusterDomain }}
          #  - name: global.localClusterDomain
          #    value: {{ coalesce $.Values.global.localClusterDomain $.Values.global.hubClusterDomain }}
      destination:
        server: {{ coalesce .destinationURL "https://kubernetes.default.svc" }}
        namespace: {{ coalesce .namespace $namespace }}
{{- end }}
---
