---
- name: Parse and load secrets
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    secrets_role: 'vault_utils'
    pattern_name: 'common'
    pattern_dir: '.'
  tasks:
    - name: "Run secret-loading pre-requisites"
      ansible.builtin.include_role:
        name: '{{ item }}'
      loop:
        - cluster_pre_check
        - find_vp_secrets

    # find_vp_secrets will return a plaintext data structure called values_secrets_data
    # This will allow us to determine schema version and which backend to use
    - name: Determine how to load secrets
      ansible.builtin.set_fact:
        secrets_yaml: '{{ values_secrets_data | from_yaml }}'

    - name: Determine role to use to load secrets
      ansible.builtin.set_fact:
        secrets_role: 'k8s_secret_utils'
      when:
        - secrets_yaml['backingStore'] | default('vault') == 'kubernetes'
        - secrets_yaml['version'] | default('2.0') >= '3.0'

    - name: Load secrets using designated role
      ansible.builtin.include_role:
        name: '{{ secrets_role }}'
