apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: px-demo-postgres-config
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
data:
  POSTGRES_DB: benchdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  PGDATA: /var/lib/postgresql/data/pgdata
