apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.1-alpine
        command:
        - /bin/bash
        - -c
        - |
          while [ 1 ];
          do
            pg_isready
            if [ "$?" -eq "0" ]
              echo "Postgres ready for connections"
              createdb -U admin sampledb
              pgbench -U admin -i -s 70 sampledb
              pgbench -U admin -c 1 -j 1 -T 60
              exit 0
            fi
            echo "Postgres not ready for connection yet"
            sleep 10
          done
        envFrom:
          - configMapRef:
              name: px-demo-postgres-config
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: rwo-demo-postgres-data
