---
- name: Check for secrets namespace
  kubernetes.core.k8s_info:
    kind: Namespace
    name: "{{ secrets_ns }}"
  register: secrets_ns_rc
  until: secrets_ns_rc.resources | length > 0
  retries: 20
  delay: 45

- name: Inject k8s secrets
  no_log: '{{ override_no_log | default(True) }}'
  kubernetes.core.k8s:
    definition: '{{ item }}'
  loop: '{{ kubernetes_secret_objects }}'
