---
- name: Parse secrets data
  no_log: '{{ override_no_log | default(true) }}'
  parse_secrets_info:
    values_secrets_plaintext: "{{ values_secrets_data }}"
  register: secrets_results

- name: Return kubernetes objects
  no_log: '{{ override_no_log | default(true) }}'
  ansible.builtin.set_fact:
    kubernetes_secret_objects: "{{ secrets_results['kubernetes_secret_objects'] }}"
