apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: job-wait-for-portworx
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
      - image: quay.io/hybridcloudpatterns/utility-container
        command:
        - /bin/bash
        - -c
        - |
          num_px_pods=$(oc get pod -l name=portworx -n {{ .Values.namespace }} | wc -l)
          while [ 1 ];
          do
            num_px_pods_ready=$(oc get pod -l name=portworx -n {{ .Values.namespace }} |grep -P '\s+([1-9]+[\d]*)\/\1\s+' | wc -l)
            if [ "$num_px_pods_ready" -eq "$num_px_pods" ]; then
              echo "Portworx is ready, continuing."
              exit 0
            fi
            echo "Portworx is not yet ready, waiting."
            sleep 15
          done
        name: wait-for-portworx-ready
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: portworx-demo-sa 
      serviceAccountName: portworx-demo-sa
      terminationGracePeriodSeconds: 600 
