---
# Vault path for the demo value must match overrides/values-openshift-sscsi-vault-config-demo.yaml
# (SecretProviderClass objects[].secretPath).

global:
  hubClusterDomain: hub.example.com
  localClusterDomain: region-one.example.com

clusterGroup:
  isHubCluster: true

image:
  repository: registry.access.redhat.com/ubi10/httpd-24
  tag: "10.0-1755779646"
  pullPolicy: IfNotPresent
