apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-15"
  namespace: {{ .Values.pxnamespace }} 
  name: portworx-demo-px-ns-role
rules:
- apiGroups: ["*"]
  resources: ['pods','storageclusters']
  verbs: ['get','list']
