apiVersion: v1
kind: ServiceAccount
metadata:
  name: portworx-demo-sa
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-hook: "PreSync"
    argocd.argoproj.io/sync-wave: "-10"
